insert into ercProverbNew values(11,'Confidence begets confidence; Security begets Secure Business',0)
insert into ercProverbNew values(12,'Good fences make good neighbors; Good Awareness makes good Security professionals',0)
insert into ercProverbNew values(13,'Health is wealth for an individual: Secured Assets is wealth for a Business',0)
insert into ercProverbNew values(14,'Law is the solemn expression of legislative will. CIA is the Solemn expression of Information Security',0)
insert into ercProverbNew values(15,'Self trust is the first secret of success; Self trust is also the first secret of Information Security',0)
insert into ercProverbNew values(16,'Variety is the spice of life: Information Security is the Spice of Organization',0)
insert into ercProverbNew values(17,'Don’t judge a book by its cover: Don’t raise an incident without an evidence',0)
insert into ercProverbNew values(18,'Poets are born, but orators are trained: Individuals are born but Security professionals are trained',0)
insert into ercProverbNew values(19,'It’s better to be safe than sorry: Its better to ensure Security than Sorry',0)
insert into ercProverbNew values(20,'Walk the walk and talk the talk: Talk Security and Implement Security',0)


insert into ercProverbNew values(21,'When in Rome, do as the Romans do. Inside the Premises follow security principles',0)
insert into ercProverbNew values(22,'An open door may tempt a saint. An insecure device may tempt an impersonator',0)
insert into ercProverbNew values(23,'Diligence is the mother of good luck: Diligence is the mother of Securing Information',0)
insert into ercProverbNew values(24,'Rome wasn’t built in a day: Secure Organization cannot be built in a day.',0)
insert into ercProverbNew values(25,'Small faults indulged let in greater: Small faults at workplace let in security incidents',0)
insert into ercProverbNew values(26,'Find a coin pick it up: See an incident report it',0)
insert into ercProverbNew values(27,'Red sky at night, sailors delight. Clean Desk/Clear Screen at workplace is a Security professional’s delight;',0)
insert into ercProverbNew values(28,'Red sky in the morning, sailors take warning. Open Desktop employees take warning',0)
insert into ercProverbNew values(29,'A chain is no stronger than its weakest link: An organization is no stronger than its weak human defense',0)
insert into ercProverbNew values(30,'Discretion is the better part of valor: preparedness is the better part of business continuity',0)


insert into ercProverbNew values(31,'A watched pot never boils: A good security program never fails',0)
insert into ercProverbNew values(32,'Better to light a candle than to curse darkness: better to comply security practices than to report incidents',0)
insert into ercProverbNew values(33,'Cleanliness is next to Godliness: Confidentiality  is next to Integrity & Availability',0)
insert into ercProverbNew values(34,'Forewarned is Forearmed: Compliance is Confidence',0)
insert into ercProverbNew values(35,'Hard work never did anyone any harm: Securing Information forever protects organization',0)
insert into ercProverbNew values(36,'Never put off until tomorrow what you can do today: Never forget to raise an alarm if you notice an incident',0)
insert into ercProverbNew values(37,'Patience is a virtue for Humans: Information is an asset for organization; Awareness is a virtue',0)
insert into ercProverbNew values(38,'People who live in glass houses shouldn’t throw stones: Employees at a workplace should never deviate Information Security practices',0)
insert into ercProverbNew values(39,'Practice what you preach: Ensure Compliance so there is no Data breach',0)
insert into ercProverbNew values(40,'See no evil, hear no evil, speak no evil: See Incidents, hear Incidents, Report Incidents',0)


insert into ercProverbNew values(41,'You can’t make an omelette without breaking eggs: You can’t secure an organization without creating awareness',0)
insert into ercProverbNew values(42,'A verbal contract isn’t worth the paper it’s written on: Always have documented contracts.',0)
insert into ercProverbNew values(43,'All for one and one for all; Organization for information Security and Information Security for Clients',0)
insert into ercProverbNew values(44,'Early to bed and early to rise, makes a man healthy, wealthy and wise: Early to detect, Early to Act on an incident makes an organization’s security strong',0)
insert into ercProverbNew values(45,'Brevity is the soul of wit: CIA is the soul of Information Security',0)
insert into ercProverbNew values(46,'Avoid evil and it will avoid thee: Avoid incidents and it will result in compliance',0)
insert into ercProverbNew values(47,'The first step to health is to know that we are sick;The first step to information secuirty compliance is awareness',0)
insert into ercProverbNew values(48,'Garbage in, garbage out; Awareness in incidents out',0)
insert into ercProverbNew values(49,'Genius is one percent inspiration and ninety nine percent perspiration;Compliance is one percent enforcement and ninety nine percent awareness',0)
insert into ercProverbNew values(50,'Prevention is better than cure; Awareness is better than incidents',0)


insert into ercProverbNew values(51,'An ounce of prevention is worth a pound of cure - An ounce of Awareness is worth a Pound of compliance',0)
insert into ercProverbNew values(52,'Information Security is like salt, the absence of it makes the business tasteless.',0)
insert into ercProverbNew values(53,'Pride comes before the fall. – non compliance comes before an incident',0)
insert into ercProverbNew values(54,'"Well done" is better than "well said" – Compliance is better than incidents',0)
insert into ercProverbNew values(55,'A store is no sore. – Backup your important data',0)
insert into ercProverbNew values(56,'Confidence is the companion of success. – Information Security is the companion of a secure Organization',0)
insert into ercProverbNew values(57,'There is nothing new under the sun. – there is nothing new in being compliant',0)
insert into ercProverbNew values(58,'Think before you speak. – Think before you click',0)
insert into ercProverbNew values(59,'Wade not in unknown waters. – Never open unknown/suspicious emails',0)
insert into ercProverbNew values(60,'People only throw stones at trees with fruit on them. – Beware of Hackers prying for confidential data',0)


insert into ercProverbNew values(61,'Walk softly, carry a big stick. –  refuse to divulge confidential information to social engineers',0)
insert into ercProverbNew values(62,'Where there is a will, there is a way. – Where there is Information Security, there is a stakeholder Goodwill',0)
insert into ercProverbNew values(63,'He that sows the wind shall reap the whirlwind. – Compliance to Information Security controls  shall reap Customer Confidence',0)
insert into ercProverbNew values(64,'Good wine needs no bush. – Good Security practice needs no Introduction.',0)
insert into ercProverbNew values(65,'The wolf finds a reason for taking the lamb. – Beware, intruders have a reason to exploit vulnerabilities',0)
insert into ercProverbNew values(66,'It takes all sorts of people to make a world. – It takes all employees to make Information Security a Success',0)
insert into ercProverbNew values(67,'A good name is the best of all treasures.  –A good Reputation is the best of all treasures for an organization',0)
insert into ercProverbNew values(68,'Still tongue makes a wise head. –  Beware of Social Engineers',0)
insert into ercProverbNew values(69,'Every Action has an equal and opposite reaction likewise every action of ours has a rewarding or penalizing act from security perspective.',0)
insert into ercProverbNew values(70,'The early bird catches the worm, vigilance  catches incidents',0)


insert into ercProverbNew values(71,'A good mind possesses a kingdom, Good information security attracts business',0)
insert into ercProverbNew values(72,'Civility costs nothing. Awareness costs nothing',0)
insert into ercProverbNew values(73,'Do right and fear no one. Follow the Information Security Policy and Fear none.',0)
insert into ercProverbNew values(74,'Nothing hides under the Sun. At workplace, your actions are monitored.',0)
insert into ercProverbNew values(75,'Honesty is the best policy. Compliance is the best policy',0)
insert into ercProverbNew values(76,'Is better to light a candle than to curse the darkness. Its better to be aware and handle the threats than to cry about the vulnerabilities.',0)
insert into ercProverbNew values(77,'It takes one bad apple to spoil the barrel! One Major Incident will take away Customer trust on us (or) One person’s mistake can ruin the customer trust',0)
insert into ercProverbNew values(78,'Just between you and me. The Information is Confidential. Protect it.',0)
insert into ercProverbNew values(79,'Many hands make  work light. Many people have to work together for Compliance.',0)
insert into ercProverbNew values(80,'Success is a journey not a destination, Information security is a journey not a destination.',0)


insert into ercProverbNew values(81,'Secret of success is stop wishing start doing, Secret of a secured orgnz is stop complaining and start complying.',0)
insert into ercProverbNew values(82,'To live a creative life we must lose our fear of being wrong , To make a secure organization report incidents when noticed',0)
insert into ercProverbNew values(83,'Fortune favors the bold, security awareness favors the Business.',0)
insert into ercProverbNew values(84,'A chain is only as strong as its weakest link. Security of an organization is as strong as its employee’s awareness',0)
insert into ercProverbNew values(85,'Cometh the hour, cometh the man. Cometh Strong security controls, Cometh Goodwill from Clients',0)
insert into ercProverbNew values(86,'Discretion is the better part of valor. Being cautious is better than to be merely be punished',0)
insert into ercProverbNew values(87,'Habit is second nature. Information Security Practices are first.',0)
insert into ercProverbNew values(88,'A new broom sweeps clean. Patches keep systems clean.',0)
insert into ercProverbNew values(89,'An empty bag will not stand upright. Policies and procedures build a strong security culture',0)
insert into ercProverbNew values(90,'Avoid evil and it will avoid thee. Follow Infosec controls to avoid incidents',0)


insert into ercProverbNew values(91,'Ask no questions and hear no lies. Don’t trust the rumors and believe only data.',0)
insert into ercProverbNew values(92,'Fine feathers make fine birds. Best Practice makes an organization better.',0)
insert into ercProverbNew values(93,'A straw will show which way the wind blows .A small incident will show the vulnerabilites.',0)
insert into ercProverbNew values(94,'Life does not get better by chance it gets better by change. Business gets better by following info sec policies at workplace.',0)
insert into ercProverbNew values(95,'The squeaky wheel gets the grease. Audits help us fix it.',0)
insert into ercProverbNew values(96,'A watched pot never boils. Real time monitoring helps to fix issues.',0)
insert into ercProverbNew values(97,'One man’s trash is another man’s treasure. Beware of dumpster divers.',0)
insert into ercProverbNew values(98,'A penny saved is a penny earned. Data backed up is treasure during disaster.',0)
insert into ercProverbNew values(99,'you can lead a horse to the water but you cannot make it drink; you can lead a awareness program but compliance is individual responsibility',0)
insert into ercProverbNew values(100,'There is no escalator to success ONLY steps; there is no short cut for information secuirty ONLY Awareness',0)


insert into ercProverbNew values(101,'To make soap we need oil; but to clean oil we need soap : to ensure compliance we need to be aware',0)
insert into ercProverbNew values(102,'When in doubt consider all information confidential',0)
insert into ercProverbNew values(103,'Time and tide waits for none;  Hackers always await  Vulnerabilities/weakness in the system',0)
insert into ercProverbNew values(104,'Building capacity dissolves differences. It irons out inequalities; Building awareness dissolves non compliance. It minimizes incidents',0)
insert into ercProverbNew values(105,'if you don’t know the sender, it might be an imposter',0)
insert into ercProverbNew values(106,'It ONLY takes one unsecured Device to cause a Data Breach. Make sure your devices are password protected and safely stored when not in use.',0)
insert into ercProverbNew values(107,'What you share with an individual can easily be shared with others. Watch what you post on Social Media.. Do Not post confidential information on social media',0)
insert into ercProverbNew values(108,'Anybody can steer a ship when the sea is calm.  None can salvage a business when there is data breach.',0)
insert into ercProverbNew values(109,'You would never leave your Wallet on your desk, likewise do not leave your computer/ workstation unlocked',0)
insert into ercProverbNew values(110,'If you reveal your secrets to the wind, you should not blame the wind for revealing it to trees… Kahlil Gibran',0)